---
title: Python for Data Science - Numpy
author: Vidyasagar Bhargava
date: '2019-07-26'
categories:
  - Tutorials
tags:
  - Data Science
  - Numpy
  - python
slug: python-for-data-science-numpy
keywords:
  - tech
---

#### Numpy  

Numpy (Short for Numerical Python) provides an efficient interface to Store and operate on arrays of number. Its somewhat looks like python's builtin `list` type but much more efficient as the arrays grows in size.  


```{python} 
import numpy as np
np.__version__
```


> How numpy improves the performances as compare to base python operartions on arrays of data?  


Python is dynamic typing language unlike C and JAVA which are statically type language that requires variable to be declare explicitly.  

Let's take a C code example  

```
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

Now the equivalent operation in python can be written as :   

```{python}
result = 0
for i in range(100):
    result +=i
```


If you notice the difference data type of each variables are explicitly declared in C while in python types are dynamically inferred. So we can assign any type of data to any variable in python.  


```{python}
#python code
x = 4
x = "four"
```

Same thing in C would lead to compilation error.

```
/* C code */
int x = 4;
x = "four" //fails

```

This type of flexibility makes python convenient and easy to use but this type-flexibility also points to the fact that python variables are more than just their value. They also contains the extra information about the type of value.  


> The standard python implementation was written in C.


When we define an integer in python  for example `x = 100` is not just a "raw" integer. It is actually a pointer to a compound C structure which contains several values.   If we see the source code of python 3.4 or above we find that integer in python actually contains 4 pieces.  

-  `ob_refcnt` a reference count that helps Python silently handle memory allocation and deallocation  
-  `ob_type`  which encodes the type of the variable  
-  `ob_size`  which specifies the size of the following data members  
-  `ob_digit` which contains the actual integer value that we expect the Python variable to represent.  



> A C integer is a label for a position in memory whose bytes encode an integer value. A python integer is a pointer to a position in a memory containing
all the python object information, including the bytes that contains the integer value.All this additional information information in Python types comes at additional cost.  




# Fixed type arrays in python  

The built in array module helps in creating dense arrays of a uniform type

```{python}
import array
L = list(range(10))
A = array.array('i',L)
A
```

Here `'i' `is a type code indicating the contents are integers.


Python's `array` object provides efficient storage of array-based data, NumPy adds to this efficient operations on that data.

```{python}
import numpy as np
np.array([1,2,3,5,6])
```
 

> NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible.  


```{python}
np.array([3.14, 1, 2.0,3 ,5])
```


Explicity set the data type using keyword `dtype`.  

```{python}
np.array([1,2,3,4], dtype='float32')
```


numpy array can be multi-dimensional unlike python lists.  

```{python}
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])
```


Creating Arrays from scratch using routines built into NumPy. 

```{python}
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

# Create a 3x5 floating-point array filled with ones
np.ones((3,5), dtype=float)

# Create a 3x5 array filled with 3.14
np.full((3,5),3.14)

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))
# Create a 3x3 identity matrix
np.eye(3)

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

```


Now we will discuss few categories of basic array manipulation here :  


-  Attributes of arrays    
-  Indexing of arrays         
-  Slicing of arrays    
-  Reshaping of arrays     
-  Joining and splitting of arrays    



```{python}
import numpy as np
np.random.seed(0) #for reproducibility

x1 = np.random.randint(10, size= (3,4,5))
x1
```

#### Attributes of arrays

Each array has `ndim` , `shape` , `size`, `dtype`, `itemsize`, `nbytes` attributes.

```{python}
print(x1.ndim)
print(x1.shape)
print(x1.size)
print(x1.dtype)
print(x1.itemsize)
print(x1.nbytes)
```


#### Indexing of arrays

python is zero indexed unlike R where indexing starts from 1.

```{python}
x1 = np.array([1,2,3,5,8])
x1[0]
x1[4]
x1[-1]
x1[-2]

```


#### Slicing of arrays  

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character.  

```
x[start:stop:step]
```


```{python}
x
x = np.arange(10)
x[5:] # elements after index 5
x[4:7] # middle sub-array
x[::2]  # every other element
x[::-1]  # all elements, reversed
x[5::-2]  # reversed every other from index 5
```

lets take another example using multi-dimensional sub-arrays.  


```{python}
x2 = np.random.randint(10,size= (3,4))
x2
```


```{python}
x2[:2, :3]  # two rows, three columns
```

```{python}
x2[:3, ::2]  # all rows, every other column
x2[::-1, ::-1]
```

```{python}
x2

```
 one common needed routine is accessing single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon `(:)`

```{python}
print(x2[:,0])
print(x2[0,:])
```



> 👉 In numpy array slices return views rather than copies  of array data. While in list slices will be copies.


let's take an example.  

```{python}
print(x2)
```

The above is our 2-dimensional array.  

```{python}
x2_sub = x2[:2,:2]
print(x2_sub)
```

Now if we modify this subarray, we will see that original array is changed.!

```{python}
x2_sub[0,0]=99
print(x2_sub)
```


Observe below :  
 
```{python}
print(x2)
```

> 👉 The above property is useful while working with large datasets.  




Despite nice features of array views its sometimes  useful to instead explicitly copy the data with in an array or a subarray. This can be mostly easily  done with `copy()` method.  

```{python}
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)
```


if we now modify this subarray, the original array is not touched.  
```{python}
x2_sub_copy[0,0] = 42
print(x2_sub_copy)
```


```{python}
print(x2)
```



##### Reshaping of arrays  

lets take an example  

```{python}
grid  = np.arange(1,10).reshape((3,3))
grid
```

```{python}
x = np.array([1,2,3])
x.reshape((1,3))
```

```{python}
x[np.newaxis, :]
```




```{python}
x.reshape
```



```{python}
x[:, np.newaxis]
```






#### Array concatenation and splitting   

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines `np.concatenate`, `np.vstack`, and `np.hstack`, `np.concatenate` takes a tuple or list of arrays as its first argument, as we can see here:

```{python}
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])
```
It can also be used for two-dimensional arrays:

```{python}
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
                 
```


 concatenate along the first axis

```{python}
np.concatenate([grid, grid])
```

 concatenate along the second axis (zero-indexed)

```{python}
np.concatenate([grid, grid], axis=1)
```

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:


```{python}
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])
```





```{python}
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])
```



#### Splitting of Arrays  

Opposite to concatenation we have splitting which is implemented by the functions `np.split` ,  `np.hsplit` and  `np.vsplit`.  

For each of these, we can pass  a list of indices giving the splits points :



```{python}
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)
```




```{python}
grid = np.arange(16).reshape((4, 4))
grid
```



```{python}
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
```


```{python}
left, right = np.hsplit(grid, [2])
print(left)
print(right)
```



#### List Vs Array



```{python}
#Lets consider a list

L  = [1,2,3]

# Lets consider an array
A  = np.array([1,2,3])
```


Lets print each element of List  

```{python}


for e in L:
    print(e)
```


Lets print each element of Array
```{python}
for e in A:
    print(e)
```


We don't see any difference here. Let's append some value in both `list`  

```{python}
L.append(4)
L
```


now let's see what happens when we append value to numpy array.  

```
A.append(4)
```

> So there is no method that append in numpy array.  

There is another method to append value to list.  
```{python}
L = L + [5]
L
```

Lets try with numpy array  
```
A = A + [4, 5]
A
```

It also doesn't work.


Now let's try vector addition. To make simple we will add vector to itself.  

```{python}
L2 =[]
for e in L:
    L2.append(e + e)
L2
```


How to do in numpy? 

```{python}
A + A
```

It exactly did what we wanted.  

> `+` sign in list does concatenation however with numpy array it does vector addition. If you have matrix which is 2 dimensional array it will do matrix addition.  


Lets do another operation on list and numpy array.  


```{python}
2*A
```

lets try with list  

```{python}
2*L
```

> If you want to multiply every element of list you have to use for loop.

Now let's try element wise squaring

```{python}
L2 =[]
for e in L:
    L2.append(e*e)
    
L2
```

> L**2 will give error. Try urself.  


Lets try with numpy   

```{python}
A**2
```

> In numpy most function work element wise.  

Some operation on numpy array  
```{python}
np.sqrt(A)
np.log(A)
np.exp(A)
```

For doing above operation on list you need to use for loop and individually apply the operation. 

> numpy array is more convenient in representing the vector as comparison to list. As to do operation on list we need to use for loop. You will see now how for loop in python is very slow.  


#### Dot Product  
Dot product is type of multiplication you can perform on vectors.  There are two definition of dot product.  

1. a\cdot b\ =\ a^T\ b

2. a\cdot b\ = \left|a\right|\left|b\right|\cosθ



```{python}
a = np.array([1,2])
b = np.array([3,4])
dot = 0
for e, f in zip(a,b):
    dot += e*f
dot
```


another interesting operation numpy array is to multiply array together.  

```{python}
a*b
```

So this gives us element wise multiplication of two arrays.  Now we need to sum everything together.  

```{python}
np.sum(a*b)
```

> Sum function is instance method of numpy array itself.  

so an alternative way is  
```{python}
(a*b).sum()
```

There is more convenient way in numpy  

```{python}
np.dot(a,b)
#or
a.dot(b)
```


lets calculate the cosine angle using two available formula.

```{python}
# Calculating the magnitude `a` using simple method

amag = np.sqrt((a*a).sum())
amag
```


numpy has function for the same it is part of `linalg` module of numpy.  

```{python}
amag = np.linalg.norm(a)
amag
```

We get the same answer.  



Lets calculate the cosine angle :-  


```{python}
cosangle = a.dot(b)/(np.linalg.norm(a)* np.linalg.norm(b))
cosangle
angle = np.arccos(cosangle)
angle
```
























