---
title: Basic python crash course - Part 3
author: Vidyasagar Bhargava
date: '2019-11-15'
slug: basic-python-crash-course-part-3
categories:
  - python
tags:
  - python
keywords:
  - tech
---


### Table of Contents  

1. [**Role of underscore**](#role-of-underscore-in-python)  
2. [**Role of Asterisk**](#role-of-asterisk-in-python)  
3. [**Decorators**](#decorators-in-python)  



------------------------------------------------  
### <a id="#role-of-underscore-in-python"></a> 1. Role of underscore(_)  

Underscore (_) is a unique character in python. It has special meaning in different situations.  

Lets see first situation where it automatically stores the value of last expression and can be assign value to another variable. Check below example.   

```{python}
5+4
_
_ + 9

a = _
a
```



Secondly you can use it as variable in loop. Lets take an example.  

```{python}

for _ in range(4):
    print(_)
```


Thirdly (_) can be used to name variables,functions and classes etc..

* Single Pre Underscore (_variable)   
* Single Post Underscore (variable_)  
* Double Pre Underscore (__variable)  
* Double Pre and Post Underscore (__variable__)  



> Single Pre Underscore is used for internal use only



```{python}
#single Pre underscore := _variable
class SinglePreUnderScore:

    def __init__(self):
            self.name = "Ram"
            self._age = 21

obj = SinglePreUnderScore()
print(obj.name)
print(obj._age)

```

You can access single underscore variable as in above case however when it effects the name that
are imported from the module.  

Lets create a file name myfile

```{python}
# filename = myfile.py

def func():
    return "Vidya"


def _private_func():
    return 7
```



Now if you import all the names from myfile.py(like `from myfile import *`), python doesn't import the names which starts with single Pre underscore.  However you can avoid that error by importing normally (like `import myfile`).  



























