---
title: Python for Data Science - Pandas
author: Vidyasagar Bhargava
date: '2019-07-28'
categories:
  - Tutorials
tags:
  - Pandas
  - Python
slug: python-for-data-science-pandas
keywords:
  - tech
---


```{r setup, include=FALSE}
library(knitr)
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
```


Pandas is a package which is built on top of Numpy and provides efficient implementation of `DataFrame`. These dataframes are multidimensional arrays with attached row and column labels and often with heterogenous types.In this post we will focus on `Series`, `DataFrame` and related structure effectively.  



#### Installing and Using Pandas

Once pandas is installed you can import and check the version.  


```{python}
import pandas as pd
pd.__version__
```


#### Pandas Objects  

There are three fundamental pandas objects or structures : the `Series`, `DataFrame` and `Index`.  





#### The Pandas Series Object  

A Pandas `Series` is a one-dimensional array of indexed data. It can be created from a `list` or `array` as follows :  


```{python}
data = pd.Series([0.23,1,3,5.89,67])
data
```

As `Series` wraps both sequence of values and sequence of indices, which we can access with the `values` and `index` attributes. 


** Value**

```{python}
data.values
```


```{python}
data.index
```

Accessing data by associated index.

```{python}
data[2]
```


> 👉  Pandas Series is much more flexible and general as compare to one-dimensional numpy array.  



Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.

This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.



```{python}
data = pd.Series([0,2,4,6,8], index = ['a','b','c','d','e'])
data
```



#### Series as specialized dictionary


Constructing a `series` object directly from a Python dictionary.  

```{python}
mob_dict = {'Nokia': 37834,
'Samsung':234893,
'Apple':93849,
'Oneplus':298343}
mobile = pd.Series(mob_dict)
mobile
```

> By default, a Series will be created where the index is drawn from the sorted keys.  


Accessing items in dictionary style

```{python}
mobile['Oneplus']  
```


Series also supports array style operations such as slicing

```{python}
mobile['Nokia':'Samsung']
```



#### Constructing Series objects

```
pd.Series(data, index = index)
```

where `index` is optional argument and data can be one of many entities.  

For ex:-  Data can be list or numpy array in which case index defaults to an integer sequence.



```{python}
pd.Series([2,4,5,9])
```


data can be `scalar`

```{python}
pd.Series(5, index = [100,200,300])
```


data can be dicitonary in which index defaults to the sorted dictionary keys  

```{python}
pd.Series({2:'a', 1:'b', 3:'c'})
```



#### DataFrame Object  

If series is an analog of a one dimension array with flexible indices, a dataframe is analog of a two dimensional array with both flexible row indices and flexible column names.  


```{python}
mob_dict = {'Nokia': 35,
'Samsung':65,
'Apple':16,
'Oneplus':10}
models = pd.Series(mob_dict)
models
```

We can use dictionary to construct a single two dimensional object containing this information.  

```{python}
mobiles = pd.DataFrame({'Sales' : mobile, 'models': models})
mobiles
```

> Like the Series object, the DataFrame has an index attribute that gives access to the index labels

```{python}
mobiles.index
```



```{python}
mobiles.columns
```


```{python}
mobiles['models']
```


A pandas dataframe can be constructed in many ways.Here are few examples 

- From single Series object  


```{python}
pd.DataFrame(mobile, columns=['mobile'])
```



- From list of dicts

Any list of dictionaries can be made into dataframe.

```{python}
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
data
pd.DataFrame(data)
```



- From dictionary of series objects

```{python}
pd.DataFrame({'Sales':mobile, 'models': models})
```

- From two dimensional numpy array

```{python}
import numpy as np
pd.DataFrame(np.random.rand(3, 2),
             columns=['foo', 'bar'],
             index=['a', 'b', 'c'])
```

- From numpy structured array  

```{python}
A = np.zeros(3,dtype=[('A', 'i8'), ('B', 'f8')])
A
```


```{python}
pd.DataFrame(A)
```


#### Data Indexing and Selection  



As we know a series object acts in many ways like a one-dimensional Numpy array and in many ways like a standard python dictionary.


```{python}
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a','b', 'c','d'])
data
```



```{python}
data['a']
```



```{python}
data.keys()
list(data.items())
```

you can extend a dictionary by assigning to a new key

```{python}
data['e']=1.34
data
```





#### Series as one-dimensional array


slice by explicit index

```{python}
data['a':'c']
```

slice by implicit integer index

```{python}
data[0:2]
```


masking

```{python}
data[(data > 0.3) & (data < 0.8)]
```

fancy indexing 

```{python}
data[['a','e']]
```



>  👉  When slicing with an explicit index (i.e., data['a':'c']), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice





#### Indexers: loc, iloc and ix



```{python}
data = pd.Series(['a', 'b', 'c'], index = [1,3,5])
data
```

explicit index when indexing

```{python}
data[1]
```


implicit index when slicing

```{python}
data[1:3]
```

Due to above confusion in case of integer indexes, pandas provide some special indexer attributes explicitly expose certain indexing schemes. 

First, the `loc` attribute allows indexing and slicing that always references the explicit index:


```{python}
data.loc[1]
data.loc[1:3]
```


The `iloc` attribute allows indexing and slicing that always references the implicit Python-style index


```{python}
data.iloc[1]
data.iloc[1:3]
```


A third indexing attribute, `ix`, is a hybrid of the two, and for `Series` objects is equivalent to standard []-based indexing.The purpose of the `ix` indexer will become more apparent in the context of `DataFrame`.



#### Data Selection in Data Frame  

A `DataFrame` acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of `Series` structures sharing the same index. These analogies can be helpful to keep in mind as we explore data selection within this structure.


**Data Frame as a Dictionary** 



```{python}
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data
```



The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name:



```{python}
data['area']
```

Equivalently, we can use attribute-style access with column names that are strings:

```{python}
data.area
```


This attribute-style column access actually accesses the exact same object as the dictionary-style access


```{python}
data.area is data['area']
```


> 👉 If the column names are not strings, or if the column names conflict with methods of the DataFrame, this attribute-style access is not possible.




```{python}
data.pop is data['pop']
```

> You should avoid the temptation to try column assignment via attribute.  


Dictionary-style syntax can also be used to modify the object, in this case adding a new column  

```{python}
data['Density'] = data['pop']/data['area']
data
```



** DataFrame as 2-dimensional Array

As mentioned previously, we can also view the DataFrame as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute :  


```{python}
data.values
```

With this picture in mind, many familiar array-like observations can be done on the DataFrame itself. For example, we can transpose the full DataFrame to swap rows and columns 


```{python}
data.T
```

When it comes to indexing of DataFrame objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array. In particular, passing a single index to an array accesses a row:  

```{python}
data.values[0]
```

and passing a single "index" to a DataFrame accesses a column:


```{python}
data['area']
```

Thus for array-style indexing, we need another convention. Here Pandas again uses the loc, iloc, and ix indexers mentioned earlier. Using the iloc indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:  


```{python}
data
```



```{python}
data.iloc[:3, :2]
```
Similarly, using the loc indexer we can index the underlying data in an array-like style but using the explicit index and column names:  

```{python}
data.loc[:'Illinois', :'pop']
```

The `ix` indexer allows a hybrid of these two approaches:  

```{python}
data.ix[:3, :'pop']
```


In the loc indexer we can combine masking and fancy indexing as in the following:

```{python}
data.loc[data.Density > 100, ['pop', 'Density']]
```

Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you might be accustomed to from working with NumPy:



```{python}
data.iloc[0, 2] = 90
data
```


Quick analysis of any data

```{python}
data.describe()
```

To get the complete information about the data set we can use `info()` function.  

```{python}
data.info()
```


To sort the `DataFrame`


```{python}
data.sort_values(by = ['area'], ascending=True, inplace= False)
```
>👉 Inplace = True will make changes to the data


We can sort by multiple columns as well


```{python}
data.sort_values(by = ['area', 'pop'], ascending=[True,False], inplace= False)
```

How to remove duplicate rows ?

consider below `DataFrame`


```{python}
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data
```

To sort values
```{python}
data.sort_values(by = 'k2')
```

remove duplicates

```{python}
data.drop_duplicates()
```



We can even removes duplicates based on particular column. Let's remove duplicate values from the k1 column.  

```{python}
data.drop_duplicates(subset='k1')
```










