---
title: Basic python crash course - Part 1
author: Vidyasagar Bhargava
date: '2019-07-06'
slug: basic-python-crash-course
categories:
  - python
tags:
  - python
keywords:
  - tech
---

Python is most popular programming language among data scientists across the world and like high level languages, python is easy to read, take less time to write and is portable.  So in this post we will learn about basics of python which includes variables, numbers conditionals, functions, list, dictionary, set, expression etc...    



```{r setup, include=FALSE}
library(knitr)
library(reticulate)
knitr::knit_engines$set(python = reticulate::eng_python)
```

### Table of Contents:-  

1. [**Variable, Numbers and Strings**](#variable-numbers-and-strings)    
2. [**Conditionals**](#conditionals)  
3. [**Functions**](#functions)  
4. [**List, dictionary, Set, Expression**](#list-dictionary-set-expression)  


### <a id="#variable-numbers-and-strings"></a> 1. Variable, Numbers and Strings  

**Variable**    

A variable is simply a container for data.  

```{python}
#for example
pi = 3.14
print(pi)
```

**Numbers**     

Numbers help in carrying out calculations. In python number are categorized in different data-types.
A type is way to define various data structures and containers and define the functionality associated with them.  

> 👉 Types are implemented in python as classes.  

To check if a number belongs to particular class use ```isinstance()``` and provide number as first argument and class name as second argument.  


```{python}
# isinstance(object, class)
isinstance(2, int)
```

There are three numeric types in python :-  

1. int for integers  
2. float for decimals  
3. complex for complex numbers  


**Strings**  

Strings are sequences of characters just like your name.  

```{python}
#How to create a string ?

myname = 'Vidyasagar Bhargava'
print(myname)
print(f"The type of string is {type(myname)}")

```


In above example we used f-strings which provides a concise and convenient way to embed python expressions inside string literals for formatting.   



> 👉 While defining string you can use single and double quotes for a single line of characters. Multiple lines are generally put in triple quotes.  

**String Methods**  

index   

```{python}
#to get index of substring in a string  
print(f"The index of 'V' in myname is {myname.index('V')}")
print(f"The index of 'a' in myname is {myname.index('a')}")
```

> 👉 Python is zero-indexed unlike R.


To check if a substring present in string 

```{python}
"i" in "Vidyasagar"
"A" in "Vidyasagar"
```


Breaking string based on some rule  

```{python}
new_string = "1:2:3:4"
new_string.split(":")
```


> 👉 Space is default parameter in split method.   


  To access individual character in string.  

```{python}
# myname = Vidyasagar Bhargava defined earlier
print(myname[4]) #access fifth letter  
print(myname[-4]) #access 4th letter from the end
```




----------------------------------------------------------------------------------------------------

### <a id="#conditionals"></a> 2. Conditionals  
 
**Loops**  

If you want to run an operation on a collection of items, then you can do it using for loops.  


```
for item in iterable:
    your code here.
```


> 👉 An iterable is any object that can be looped on such as list, tuple, string etc.  


```{python}
countries = ["India", "United Kingdom", "United States", "China", "France"]

for country in countries:
    print(country)
```


nested ```for``` loops  

```{python}
for country in countries:
    string_size = 0
    for alphabet in country:
        string_size += 1
    print(f"Name of country: is {country} which has length {string_size}")
```

looping on both indexes and items  

```{python}
for index, country in enumerate(countries):
    print(f"index is {index}")
    print(f"Country is {country}")
    print("--------------------------")
```


**While Statements**   

Use ```while``` statements when the block of code has to be run till the condition is true.  

```
while condition:
    code block
```


We will use above countries example.  

```{python}
length = len(countries)
i = 0
while i < length:
    print(countries[i])
    i += 1
```


#### If statements  

Below is skeleton for ```if.. elif.. else``` syntax  


```
if condition1:
        code_block1
elif condition2:
        code_block2
else:
       code_block3
```

let's take an example  

```{python}
num = 10
if num == 12:
    print("number is 12")
elif num == 10:
    print("number is 10")
else: 
    print("num is neither 10 nor 12")
```


Nested ```if``` statements  

```{python}
num = 10
if num > 5:
    if num < 20:
        print("num is between 5 an 20")
```



--------------------------------------------------------------------------------------------------------------

### <a id="#functions"></a> 3. Functions   

-  Creating a function  
-  Calling a function  



**Creating a function**    

Here is skeleton of function defintion  

```
def name_of_the_function(arguments):
    '''
    function doctring
    '''
    body of the function
    return the return value or expression

```

let's take an example  

```{python}
def add_numbers(num1, num2):
    '''returns  the sum of num1 and num2''' 
    result = num1 + num2
    return  result
    
```


**Calling a function**    

```{python}
add_numbers(5,6)
```

--------------------------------------------------------------------------------------------------

### <a id="#list-dictionary-set-expression"></a> 4. List, Dictionary, Set, Expression  

**List**

- List is a data structure which can be used to store multiple data at once.  
- The indexing is done with 0 as first index.  
- They are great to preserve sequence of data and then to iterate over them later for various purposes.  


```{python}
# Creating a list  

mobiles = ['nokia','samsung', 'apple','htc', 'oneplus', 'sony']
print(mobiles[0])
```


Two dimensional list

```{python}
mobiles = [['nokia','samsung', 'apple'],['htc', 'oneplus', 'sony']]
print(mobiles[0][1])
```

**Methods in lists**

- ```append()```   
- ```insert()```
- ```extend()```
- ```index()```
- ```remove()```
- ```pop()```
- ```sort()```
- ```reverse()```
<br>
To add elements in the list use ```append()```  method.  


```
list.append(elem)

```
example  

```{python}
# append()
mobiles = []
mobiles.append('googlepixel')
mobiles.append('lg')
mobiles.append('micromax')
print(mobiles)
```


To add elements to the list at a particular index use ```insert()``` method.  

```
list.insert(index, element)
```
example  
  
```{python}
# initiliazing a list
mobiles = ['nokia','samsung', 'apple','htc', 'oneplus', 'sony']
print(mobiles)

#insert 'googlepixel' at 2nd position 
mobiles.insert(2, 'googlepixel')
print(mobiles)
```


To add another list to the list use ```extend()``` method.  

```
list.extend(another_list)
```

example 

```{python}
langs = ['R','Python','Scala']
langs.extend(['Julia', 'C++'])
print(langs)
```


To get the index number of element in the list use ```index()``` method.  

```
list.index(elem)
```

example

```{python}
index_of_Julia = langs.index('Julia')
print(index_of_Julia)
```


To remove elements from the list use ```remove()``` method. 

```
list.remove(elem)
```

example 

```{python}
langs.remove('C++')
print(langs)
```


To remove last element of the list use ```pop()``` method.  

```
list.pop()
```
example  

```{python}
#print previous list
print(langs)

#pop the list
langs.pop()

#print current list
print(langs)
```


> 👉 If the index is provided in ```pop()``` method then it will remove element at particular index.  


```{python}

numbers = [10, 20, 30, 40, 50]

numbers.pop(1)

print(numbers)
```


To sort the list use ```sort()``` method.  

```
list.sort()
```

example  

```{python}
# initialize an unsorted list 

numbers = [7,1,9,3,5,2]
print(numbers)

# sort the list 
numbers.sort()
print(numbers)
```


To reverse the list use ```reverse()``` method. 

```
list.reverse()
```

```{python}
# initialize  a list
numbers = [7,1,9,3,5,2]
print(numbers)

# reverse the list
numbers.reverse()
print(numbers)
```


#### Functions over lists :

-  ```len()```
-  ```enumerate()```
-  ```sorted()```


To get the length of list use ```len()``` function.  


```{python}
mobiles = ['nokia','samsung', 'apple','htc', 'oneplus', 'sony']
print(f"The length of the list mobile is {len(mobiles)}")
```

To get the index and value of the list use ```enumerate()``` function.  

```{python}
for indx,name in enumerate(mobiles):
    print(f"Index is {indx} for mobile :{name}")
```

To sort over the list use ```sorted()``` function.  However unlike ```sort()``` method here original list is preserved.  


```{python}
#initialize the list
numbers = [5, 6,2,1,8,7]

#get the sorted list  
print(sorted(numbers))

#get the original list
print(numbers)
```

---------------------------------------------------------------------------------------------------


#### Dictionary  

A dictionary is set of unordered key, value pairs.The keys must be unique and they are stored in an unordered manner.  


```{python}
#creating a dictionary 

employees  = {'name' : ['Sundar','Elon', 'Satya'], 'company' : ['Google', 'Tesla', 'Microsoft'], 'birth_country' :['Ind','SA', 'Ind']}

#printing the dictionary
print(employees)

print(type(employees))

```



**Getting values in a dictionary**    

```{python}
print(employees['name'])
```
 
You can use ```get()``` method as well to get the values. The only difference is that in ```get()``` method you can set default value.  

```{python}
print(employees.get('name'))

print(employees.get('designation', 'default'))
```


**looping over dictionary**  

```{python}
for k, v in employees.items():
    print(f"key is : {k}")
    print(f"value is : {v}")
    print("--------------------")
```


**Adding elements to dictionary**  

```{python}
employees ={}
employees['name'] = 'Jeff'
employees['company'] = 'Amazon'

print(employees)
```

Using ```update()``` method we can add other dictionary.

```{python}
other_dictionary = {'birth_country' : 'US'}
employees.update(other_dictionary)
print(employees)
```

**Delete elements  of a dictionary**  

```{python}

# initiailize a dictionary  

employees  = {'name' : ['Sundar','Elon', 'Satya'], 'company' : ['Google', 'Tesla', 'Microsoft'], 'birth_country' :['Ind','SA', 'Ind']}
print(employees)

# delete the key value pair with key 'birth_country'

del employees['birth_country']
print(employees)
```


> 👉 There is another way using ```pop()``` method which has advantage like if there is non-existent key you can pass default value.


```{python}
print(employees.pop('Salary', None))
```

--------------------------------------------------------------------------

#### Sets

-  A Set is an unordered collection of data with no duplicate elements.  
-  Sets are iterable and mutable.  


Set can be created by calling the ```set()``` function with a sequence or other iterable object.    

```{python}
# creating a empyty set
SetA = set()
print(SetA)

# creating a set with a string  
SetA = set("Vidyasagar")
print(SetA)

# Creating a set with a list 
SetA = set(["India", "China", "US"])
print(SetA)

#creating a set withlist of repeated number
SetA = set([1,2,4,5,5,5,6,6,7,7,7])
print(SetA)
```



> 👉 Set is useful in removing duplicate enteries.


**Methods on Sets**

-  ```add()```
-  ```update()```
-  ```discard()```
-  ```remove()```
-  ```copy()```
-  ```clear()```
-  ```pop()```



To add element to a set use ```add()``` method.  


```
set.add(element)
```

example  

```{python}
SetA = set([1,2,3,4])
print(SetA)

#adding an element 5

SetA.add(5)
print(SetA)



```

> 👉 You can add a tuple to set using ```add()``` method. 

```{python}
SetA = set([1,2,3,4])
print(SetA)
SetA.add((9,10))
print(SetA)
```

Using ```update()``` method we can pass list and it will update Set with the elements.

```
set.update(element)
```

example  

```{python}
SetA = set([1,2,3,4])
print(SetA)

SetA.update([5,6])
print(SetA)
```

Using ```discard()``` and ```remove()``` method you can to remove element from the set.

```{python}
SetA = set([1,2,3,4])
print(SetA)

SetA.discard(3)
print(SetA)
```


 ```remove()``` method

```{python}
SetA = set([1,2,3,4])
print(SetA)

SetA.remove(3)
print(SetA)
```


> 👉 ```discard()``` and ```remove()``` takes single element and remvoes from set howver if no value is present then ```discard()``` does not  do anything howver ```remove()``` will raise KeyError exception.  



Using ```copy()``` method we can create a shallow copy of the set.   


```{python}
SetA = set([1,2,3,4])
print(SetA)

SetB = SetA.copy()
print(SetB)
```

If you use assignment operator it will create a pointer to already existing set.  



```clear()``` method will remove all the elements from set.  

```{python}
SetA = set([1,2,3,4])
print(SetA)
SetA.clear()
print(SetA)
```

```pop()``` will remove arbitary set element.  

```{python}
SetA = set([1,2,3,4])
print(SetA)

SetA.pop()
print(SetA)
```


Other useful Set operations 


```{python}
#interaction()

SetA = set([1,2,3,4,5,6,7])
print(SetA)

SetB = set([5,6,7,8])
print(SetB)

print(SetA & SetB)

print(SetA.intersection(SetB))


#difference()
print(SetA.difference(SetB))
print(SetB.difference(SetA))

```

-------------------------------------------------- 


#### Expression  

- List Expression   
- Dictionary Expression  
- Generator Expression  
- Conditional Expression  


**List Expression**  

```
[compute(var) for var in iterable]
```
example  

```{python}
[str(x) for x in range(10)]
```

**Dictionary Expression**

```
{k,v for k in iterable}
```

example  


```{python}
{x:x**2 for x in range(5)}
```

**Generator Expression**  


```
(compute(var) for var in iterable)
```

example  

```{python}
(x for x in range(10))
list(x for x in range(10))
```


**Conditional Expression**  

```
true_value if condition else false_value
```

example  

```{python}
x = "1" if True else "2"
print(x)
```









