---
title: Machine Learning in Python
author: Vidyasagar Bhargava
date: '2019-06-14'
slug: machine-learning-in-python
categories:
  - python
  - Machine learning
tags:
  - machine learning
  - python
keywords:
  - tech
---





In this post we will see demo of  two machine learning problems using python. We will train model on two different datasets using  two  different type of machine learning algorithm one for classifier and other for regression.The learning algorithm finds the pattern in the training data which maps the input data features to target variable and it outputs an machine learning model that captures these patterns. Also we will learn about scikit-learn library in detail (coming soon). 


<style type="text/css">
   .gist{font-size:13px;line-height:18px;width:60em}
   .gist pre{font-family:Menlo,Monaco,'Bitstream Vera Sans Mono','Courier New',monospace !important}
   .gist-meta{font-family:Arial,sans-serif;font-size:13px !important}
   .gist-meta a{color:#3b5998 !important;font-weight:bold;text-decoration:none}
   .gist-meta a:hover{text-decoration:underline}
</style>

#### Demo classifier problem in python  

<script src="https://gist.github.com/vidyasagarbhargava/f54a6fcc13e1ec2d32e70ee7fdbd0790.js"></script>


<br>


#### Demo regression problem in python    


<script type="application/javascript" src="https://gist.github.com/vidyasagarbhargava/41f195a6a037bcdf4ffd522826c42c11.js"></script>


```{r, include= FALSE}
#### Shiny app embeded


#<iframe width="750" height="800" scrolling="no" frameborder="0" src #="https://hadley.shinyapps.io/cran-downloads/"></iframe>

```

